### ISSUE TITLE
Different wiring compatible with DCMI – is it possible?

### ISSUE THREAD

**Issue by psprint** [Frans-Willem/LEDMatrixHUB75#1]
I will be using DCMI together with RGB LED Matrix. For the matrix, I've followed: [Adafruit guide](https://learn.adafruit.com/32x16-32x32-rgb-led-matrix/connecting-using-a-proto-shield) that uses a protoshield. I can use Arduino protoshield thanks to **ST Zio connector** on my Nucleo-F767ZI (144-package) board.

The pins used by Adafruit are:
```
--- 32x16 Matrix ---
R1       digital 2 / PF15
G1       digital 3 / PE13
B1       digital 4 / PF14

R2       digital 5 / PE11
G2       digital 6 / PE9
B2       digital 7 / PF13

A        analog 0 / PA3
B        analog 1 / PC0
C        analog 2 / PC3

LAT/STB   analog 3 / PF3
CLK       digital 8 / PF12
OE        digital 9 / PD15
```

don't collide with DCMI (8-bit external synchro) pins:
```
--- DCMI ---
PIXCLK      PA6
HSYNC       PA4
D4          PE4
D6          PE5
D7          PE6
VSYNC       PG9
D5          PD3
D3          PC9
D2          PC8
D1          PC7
D0          PC6
```

The wiring in [Wiring.md](https://github.com/Frans-Willem/LEDMatrixHUB75/blob/master/Documentation/Wiring.md) however does collide, very often (uses PD3, PE4, PE5, PE6, PC6).

Question: **Will I be able to switch code of your library to the Arduino pin mapping?**

**Comment by Frans-Willem** [comment]
Hey,

From what I remember, my code requires (at the very least) the data (R1, G1, B1, R2, G2, B2) pins and clock pin one one GPIO port. Your current proposed wiring will, thus, not work with this code, sorry.

Either way good luck with your project, and I hope some of the ideas in this one may still help you along :)

Frans-Willem
