### ISSUE TITLE
“FRAMEBUFFER_SHIFTLEN” Definition

### ISSUE THREAD

**Issue by wz233** [Frans-Willem/LEDMatrixHUB75#2]
Dear Frans-Willem:

I read your article [96×48 full-color LED Matrix](https://fw.hardijzer.nl/?p=223), thanks for your detail explanation! I am trying to understand your code.

In the "framebuffer.h" file, you have following definitions:

```c
#define FRAMEBUFFER_SHIFTLEN	(FRAMEBUFFER_BITSPERLINE * 2)
```

I understand the macro `FRAMEBUFFER_BITSPERLINE`, it equals to <img src="http://latex.codecogs.com/gif.latex?\color{red}{32\times3\times3}" />, shouldn't the shift length also equals to `FRAMEBUFFER_BITSPERLINE`?

In your article, you have following comments:

> So if you chain 2 panels, you’d have to shift in 64 bits each time.

In your project, you chained 9 pieces of RGB LED matrix with 32x16 resolution, doesn't that mean the shift length equals to <img src="http://latex.codecogs.com/gif.latex?\color{red}{32\times3\times3}" />?

Hope you can get this message, and help me understand the trick. 

Thanks & Best Regards!

**Comment by wz233** [comment]
Sorry for any inconvenience, I guess I understood now. Since you combine clock signals with data. Space for speed and convenience. Gotcha!

**Comment by Frans-Willem** [comment]
The framebuffer is a bit of a misnomer, it's more of a GPIO-output-buffer. Seeing as it also embeds the clock signal, each data bit is in there twice: once with a 0 on the clock bit, and once with a 1.
So in a smaller (but theoretical) example, let's assume you have a device with 8 GPIO outputs, that you can write out a byte array to using DMA. Imagine connecting GPIO 0 to 6 to the input side of 7 shift registers, and GPIO7 to all the clock on those shift registers. Then if I'd want to shift out 2 bits on each shift register, I'd need to schedule 4 bytes to the DMA: 1 byte where the first 7 bits are the first input bits to the shift registers, and the final bit being 0, Another byte being identical to the first one, but now with the final bit (clock) being 1, then a byte containing all 7 second bits to the shift registers and a 0 again for the clock, and again identical byte with the clock signal set to 1.

Thus, to use to DMA-to-GPIO to shift out X bits to a number of parallel shift registers, you need X*2 entries.

I'll see if I can get back to your other questions over the e-mail tomorrow :)

**Comment by wz233** [comment]
OMG, your response just came when I got your method! I understood now. As for other questions in my email, I already got answers via your article, and I am now drawing some graph to visualize your frame buffer implementation. Hope it can help other DIYers. 

Again, thanks for your response!
